package main

import (
	"log"

	"github.com/crisywini/go-products-api/config"
	"github.com/crisywini/go-products-api/internal/handler"
	"github.com/crisywini/go-products-api/internal/middleware"
	"github.com/crisywini/go-products-api/internal/repository"
	"github.com/crisywini/go-products-api/internal/service"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
)

func main() {
	config := config.Load()
	r := gin.Default()

	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: false,
	}))

	// Database connection

	pool := repository.NewPool(config.DBUrl)
	defer pool.Close()

	// Init the rpository generated by SQLC
	queries := repository.New(pool)
	_ = queries

	// Services
	userService := service.NewUserService(queries)
	productService := service.NewProductService(queries)
	jwtService := service.NewJWTService(config.JWTSecret)

	// Handlers
	userHandler := handler.NewUserHandler(userService, jwtService)
	productHandler := handler.NewProductHandler(productService)

	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok"})
	})

	auth := r.Group("/auth")
	{
		auth.POST("/register", userHandler.Register)
		auth.POST("/login", userHandler.Login)
	}

	api := r.Group("/api")
	api.Use(middleware.AuthMiddleware(jwtService))
	{
		api.GET("/products", productHandler.ListProducts)
		api.GET("/products/:id", productHandler.GetProduct)
		api.POST("/products", productHandler.CreateProduct)
		api.PUT("/products/:id", productHandler.UpdateProduct)
		api.DELETE("/products/:id", productHandler.DeleteProduct)
	}

	log.Printf("Server up and running on port %s", config.ServerPort)
	if err := r.Run(":" + config.ServerPort); err != nil {
		log.Fatal(err)
	}
}
